name: zffanalyze
adopt-info: zffanalyze
summary: Tool to analyze and verify zff files.
description: |
  zffanalyze is used analyze and verify zff files.

  Zff (Z forensic file format) is a completley new designed file format
  to store and handle the contents and structure of a partial or entire disk image,
  physical memory or logical file/folder structures. The focus of zff is on speed,
  security and modularity in concert with forensic requirements. The modular design
  promises high maintainability and scalability. Zff is an alternative to the ewf
  and aff file formats and is not compatible with them.
base: core20
confinement: strict
parts:
  zffanalyze:
    build-packages: [ gcc ]
    plugin: rust
    source: https://github.com/ph0llux/zffanalyze.git
    override-pull: |
      snapcraftctl pull
      VERSION="$(git describe --tags --abbrev=0)"
      [ -n "$(echo $VERSION)" ] && GRADE=stable
      snapcraftctl set-version "$VERSION"
      snapcraftctl set-grade "$GRADE"
apps:
  zffanalyze:
    command: bin/zffanalyze
architectures:
  - build-on: [amd64,arm64]
